# frozen_string_literal: true

require 'fileutils'

BUILD_DIR = File.join(__dir__, 'build')
DEFAULT_FREETDS_VERSION = '1.1.6'
DEFAULT_AWS_REGION = 'us-east-1'

desc 'Build FreeTDS AWS Lambda Layer'
task :build, [:freetds_version] do |_t, args|
  version = args[:freetds_version] || ENV['FREETDS_VERSION'] || DEFAULT_FREETDS_VERSION
  image_name = "veracross/freetds:aws-lambda-layer-#{version}"

  FileUtils.rm_r BUILD_DIR, force: true
  FileUtils.mkdir_p BUILD_DIR

  system("
    docker build \
      --build-arg FREETDS_VERSION=#{version} \
      -t #{image_name} .
  ")

  system("docker push #{image_name}")

  system("
    docker run --rm \
    -v \"${PWD}/build:/build\" \
    #{image_name} \
    sh -c 'cp /var/task/build/freetds-layer-#{version}.zip /build'
  ")
end

desc 'Build and deploy FreeTDS AWS Lambda Layer'
task :deploy, [:freetds_version] => [:build] do |_t, args|
  version = args[:freetds_version] || ENV['FREETDS_VERSION'] || DEFAULT_FREETDS_VERSION
  aws_region = args[:aws_region] || ENV['AWS_REGION'] || DEFAULT_AWS_REGION

  system("
    aws lambda publish-layer-version \
    --layer-name 'freetds' \
    --description 'FreeTDS #{version} Layer' \
    --region '#{aws_region}' \
    --zip-file \"fileb://$(pwd)/build/freetds-layer-#{version}.zip\"
  ")
end

desc 'List available FreeTDS AWS Lambda Layers'
task :list_layers do |_t, args|
  aws_region = args[:aws_region] || ENV['AWS_REGION'] || DEFAULT_AWS_REGION

  system("aws lambda list-layers --region #{aws_region}")
end
